version: '3.3'

services:

  owncloud:
    image: owncloud/server:latest    # 10.13.2-arm64v8
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_TRUSTED_DOMAINS=tudominio.com  # IP # Nombre dominio válido 
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=user      # Usuario admin Owncloud
      - OWNCLOUD_ADMIN_PASSWORD=p4ssw0rd  # Contraseña admin Owncloud 
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    volumes:
      - ./files:/mnt/data

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./redis:/var/lib/redis
  
